JETSCAPE/JETSCAPE

examples/jetscape_init.xml
src/framework/JetEnergyLoss.cc
src/framework/JetScapeModuleMutex.h
src/framework/JetScapeTask.h
src/jet/AdSCFT.cc
src/jet/AdSCFTMutex.cc
src/jet/AdSCFTMutex.h
src/jet/LBT.cc
src/jet/LBTMutex.cc
src/jet/LBTMutex.h
src/jet/Martini.cc
src/jet/MartiniMutex.cc
src/jet/MartiniMutex.h

Add a mutex base class for eloss modules. Set the mutex for MARTINI, LBT and AdSCFT.
This class knows LBT, Martini and AdSCFT cannot be attached together. JetEnergyLoss calls a method of this class to check validity of its child tasks. No need to change test codes: brickTest, PythiaBrickTest,...

Add a mutex base class for eloss modules.

---

examples/LBT_brickTest.cc
examples/MUSICTest.cc
examples/PythiaBrickTest.cc
examples/SimpleValidate.cc
examples/brickTest.cc
examples/freestream-milneTest.cc
examples/hydroJetTest.cc
examples/hydroJetTestPGun.cc
src/framework/JetEnergyLoss.cc
src/framework/JetEnergyLoss.h
src/framework/JetEnergyLossManager.cc
src/framework/JetScapeSignalManager.cc
src/framework/JetScapeSignalManager.h
src/framework/JetScapeTask.h
src/jet/PartonPrinter.cc
src/jet/PartonPrinter.h

This branch removes PartonPrinter as an object-in-the-middle for hadronization. Now it does not have to be attached for hadronization and eloss sends the final state partons to the Hadronization module directly.
PartonPrinter is removed from src/framework and moved to src/jet. One may attach PartonPrinter if they need to access to the final state partons.

Removing PartonPrinter as the object in the middle for hadronization

---

src/framework/JetEnergyLoss.cc

Ensure that the final state partons are added to the same eloss pointer for hadronization.

Fix a bug in hadronization related to removing PartonPrinter.

---

src/framework/FluidEvolutionHistory.h

From the [porting guide](https://gcc.gnu.org/gcc-10/porting_to.html):
> Some C++ Standard Library headers have been changed to no longer include the <stdexcept> header. As such, C++ programs that used components defined in \<stdexcept\> or \<string\> without explicitly including the right headers will no longer compile.

Fix build on GCC 10

---

config/jetscape_master.xml
src/hadronization/iSpectraSamplerWrapper.cc
src/hydro/MusicWrapper.cc

I merged the parameterization of transport coefficientChun devs from the SIMS group into the public version of MUSIC and update the MUSIC wrapper in the JETSCAPE to allow users to pass parameters to change the temperature dependence of eta/s(T) and zeta/s(T). These modifications are useful for the hydro session during the JETSCAPE Summer School.

Add more parameters in the MUSIC wrapper for JETSCAPE Summer School

---

src/framework/SoftParticlization.cc

Fixed a typo in the variable name for detecting whether the hydrodynamic simulation is boost-invariant or not.

fixed a typo in the SoftParticlization

---

src/afterburner/SmashWrapper.cc
src/afterburner/SmashWrapper.h

For each hydro event there can be N sampler events. Particles from all N
sampler events are saved in a structure, which SMASH wrapper passes to SMASH.
Next hydro event executes new N sampler events and resets this structure, so
particles from previous hydro event are forgotten. SMASH wrapper didn't know
that and incremented the event number further instead of resetting it to 0 for
each new hydro event. That number was used as an array index, so for the second
hydro event it segfaulted.
This refs #55
Signed-off-by: Dmytro Oliinychenko <doliinychenko@lbl.gov>

Bugfix: reset SMASH event index properly

---

src/framework/JetEnergyLoss.cc
src/hydro/HydroFromFile.cc
src/jet/AdSCFT.cc
src/jet/AdSCFT.h
src/jet/LBT.cc
src/jet/LBT.h
src/jet/Martini.cc
src/jet/Matter.cc
src/jet/Matter.h

Modify the order of the MARTINI energy loss routine so that it access the hydro information after it accepts a given parton.

Modify Martini.cc to use the MUSIC hydro

---

CMakeLists.txt

Defaults to a Release build, which includes full optimizations (`-O3`). Developers will probably want to use the Debug release. Can specify when running CMake with `-DCMAKE_BUILD_TYPE="Release"` (for example)
Note that this doesn't allow for arbitrarily setting the optimization level - it's either -O3 or -O0. Such a change could come later - it most likely requires someone more knowledgeable about CMake (plus, we need to move quickly for the STAT calculations)
Closes #71

Create different options for cmake builds

---

src/hadronization/ColoredHadronization.cc

Minor change.
Changing the counter "i" from "unsigned int" to "int". Since the unsigned int can not hold a negative number, the counter "i" will go 2^{23}-1 if "--i" is called when i=0.

change unsigned int to int in ColoredHadronization

---

cmakemodules/FindPythia8.cmake
config/jetscape_master.xml
src/jet/Martini.cc
src/jet/Martini.h

* Change the name of 'alpha_s' parameter to 'alphas' for consistency with other modules.
* Prevent heavy quarks from experiencing MARTINI energy loss since MARTINI formalism is restricted by the massless approximation. Heavy quarks in MARTINI cause 'Two Eloss modules were fighting for one parton!' error with a rare probability.
* Remove personal directory in cmakemodules/FindPythia8.cmake
Tested using MATTER+MARTINI modules with 26k events in the private master branch.

MARTINI minor fix

---

external_packages/freestream-milne-external-params.patch
external_packages/get_freestream-milne.sh
src/preequilibrium/FreestreamMilneWrapper.cc

Adds support for changing the freestreaming proper time via XML `<tau0> `and `<taus>`, and the name of the configuration file _freestream_input_ itself. The freestream-milne code is patched to support this immediately after downloading with `get_freestream-milne.sh`.

Allow configuration of pre-equilibrium dynamics parameters via XML

---

external_packages/trento/src/collider.cxx

For getting the proper fraction of the cross section when the requested minimum value of the impact parameter is not zero
Same PR requested towards Trento2D

Fix sampling impact parameter

---

config/jetscape_master.xml
examples/FinalStateHadrons.cc
examples/FinalStatePartons.cc
src/framework/JetScape.cc
src/framework/JetScapeWriterFinalStateStream.cc
src/framework/JetScapeWriterFinalStateStream.h
src/reader/JetScapeReader.cc
src/reader/JetScapeReader.h

This adds a JetScape writer for final state partons and hadrons. This way, you can write final state * without having to write the full output. I performed validation with the header v2 comparing the new writer vs the FinalState* executables in the example, and the values seem to be within an absolute tolerance of 1e-3 and relative tolerance of 5e-5. I interpret this as basically our precision limit.
Also introduces a new final state hadrons and partons ascii format, known as header v2, with contains:
- additional event information
- the cross section and error stored in the same file
- more consistent spacing for parsing
- removed eta and phi to reduce storage size (since we already have the full kinematics)
A full comparison of the header v2 format is below:
Invoked …

Writer for final state partons and hadrons

---

examples/custom_examples/CLViscTest.cc
examples/custom_examples/MUSICTest.cc
examples/custom_examples/SMASHTest.cc
examples/custom_examples/TwoStagesHydro.cc
examples/custom_examples/TwoStagesHydroFromFile.cc
examples/custom_examples/freestream-milneTest.cc
examples/custom_examples/testJetScape.cc

It appears that the SMASHTest is not using the current `Jetscape()` constructor. This PR resolves this.
I also noted that a couple of other custom examples do the same and try to use `make_shared<JetScape>("./jetscape_init.xml",1)` with `jetscape_init.xml` not found in the repository anymore(?). If this fix is ok, I can go ahead and fix the other custom examples as well.

Use new Jetscape construction for SMASHTest

---

.github/workflows/plot_observables.yaml
.github/workflows/test-build-external.yaml
.github/workflows/test-events.yaml
cmakemodules/FindSMASH.cmake
docker/Dockerfile.base
docker/Dockerfile.deploy
docker/README.md
external_packages/get_smash.sh
src/afterburner/SmashWrapper.cc
src/afterburner/SmashWrapper.h

This PR bumps the versions of SMASH and Pythia to their latest versions (SMASH-2.2 and Pythia 8.307). It is required that Pythia is updated together with SMASH, since SMASH-2.2 requires Pythia 8.307.
Physics-wise no changes are expected by those updates. Some minor modifications are required for the SMASH wrapper, since some SMASH functions changed. This update includes new SMASH features however like the SMASH HepMC output.
On opening this PR is not supposed to pass the test as a new docker container including the new Pythia version is required, which is not available yet. Even though, if I see it correctly, SMASH compilation is not tested at the moment with the build test. Should we change this?
Also the test using an exakt output comparison will need to be updated as a new Pythia …

SMASH and Pythia update

---

examples/test_music_files/music_input

Change the default EoS to 9 (hotQCD EoS) for MUSIC.

Fix a segfault with the latest version of MUSIC

---

.github/workflows/test-build-external.yaml
.github/workflows/test-events-PbPb.yaml
.github/workflows/test-events-pp.yaml
src/framework/JetScape.cc
src/framework/JetScape.h

checks the XML user file against a list of tag names generated from the XML main file and warns if a tag exists in the XML user file that is not in XML main.  The generated warning message is to help protect against possible XML tag typos in a user's XML file.

warns when XML user element is not in XML main

---

src/jet/Martini.cc

Fixed the typo found by @ShuzheShi in "src/jet/MARTINI.cc".
Line1643 shall read
`rateLower = T * (d[0][0] + ...`
rather than
`rateLower = T * (d[1][0] + ...`
https://github.com/JETSCAPE/JETSCAPE/pull/134

Fixed typo in Martini interpolation

---

src/hadronization/ColorlessHadronization.cc
src/jet/LBT.cc
src/jet/Matter.cc

Add status code 22 for photons that pass through MATTER or LBT if it is already not assigned by one of the other JEL modules. Allow photons with status code 22 to pass through Colorless hadronization.

Prompt photon duplication issue fixed in medium shower

---

src/framework/JetScapeParticles.cc

This is a pull request to fix this issue, [#77](https://github.com/JETSCAPE/X-SCAPE-COMP/issues/77).
Instead of checking for light quarks in `set_t` and `t`, I set the light quark masses to 0 in the constructor. 
I'm not sure if this is the right way to do it, we can discuss if there is a better way.

Setup massless light quarks in constructor

---

external_packages/README.md

This pull request is just a documentation update, adding details to the external packages README showing how to build IP-Glasma with the jetscape/base:stable Docker image.

updated IP-Glasma instructions

---

external_packages/README.md

synchronizing the IP-Glasma documentation update, keeping JETSCAPE-3.6-RC up to date with the documentation change in main.

synchronizing docs update from main

---

src/framework/JetScapeConstants.h
src/initialstate/PGun.cc
src/initialstate/PythiaGun.cc

This PR closes #158 and closes #159. It introduces a consistent definition of hbarC and its inverse. In the pythia initial state modules, the pseudorapidity is used consistently.

Fix rapidities in pythia IS modules and make constants consistent

---

CMakeLists.txt
config/jetscape_main.xml
config/jetscape_user_FSFileTest.xml
config/jetscape_user_HydroFile.xml
config/jetscape_user_pbpb_grid.xml
config/jetscape_user_twostagehydro.xml
external_packages/smash/smash_config.yaml
src/initialstate/PythiaGun.cc
src/initialstate/PythiaGun.h
src/jet/Matter.cc

This PR fixes the bug in the Matter logic and closes #157. It introduces the `vir_factor` in the case of a negative parameter such that the parameter allows for a user handling of the maximum virtuality in this case.
The PR fixes the `sigmaGen` and `sigmaErr` reader and closes #155.
C++17 is now used to compile the code and the outdated `<useHybridHad>` flag is removed from all config files.
In the PythiaGun the xml parameters are moved to the init function and a new parameter `<softMomentumCutoff>` is introduced to handle the low momentum cutoff in the initial state. The default value is set such that the setup from the PP19 paper is implemented. In the case of a negative `vir_factor` the absolute three momentum is used to be consistent with the handling in the Matter module.

Bug fixes, C++17, softMomentumCutoff

---

src/framework/JetScapeParticles.cc

In the COMP meeting, we decided to set the CheckOrForceHadron warning to a higher verbosity level. It is not informative for the user and unnecessary to print this out in all the production runs.

Higher verbosity level for CheckOrForceHadron warning

---

external_packages/get_freestream-milne.sh
external_packages/get_iSS.sh
external_packages/get_music.sh

This PR amends the get_freestream-milne.sh, get_iSS.sh, and get_music.sh scripts to checkout specific commit hashes of these repositories, so future external repository updates won't impact the JETSCAPE 3.6.1 public release.

updates external repo get scripts to use set commit hashes

---

external_packages/trento/CMakeLists.txt

Two debug flags from Trento's CMakeLists file have been commented out so that JETSCAPE will build in Debug mode.  This addresses issue #99.  I'm considering this PR a draft because I'm not sure if this is the ideal solution or if those two flags removed from Trento's CMakeLists.txt file are needed.

removes  Debug flags from Trento's CMakeLists

---

src/hadronization/ThermPtnSampler.cc

This removes the unused include for `omp.h` in the ThermPtnSampled.cc
It solves issue #172.

Remove unused include for omp

---

README.md
src/jet/Matter.cc

Matter currently uses a random seed using srand with the current system time. Instead, Matter should initialize the random seed using the framework generated random seed for reproducibility, especially for debugging.

Eloss Matter seed corr

---

src/jet/LBT.cc
src/jet/Matter.cc

A new status code "101" is added to LBT.cc to tackle partons which has broadened. Now, energy loss module LBT doesn't push back such partons. The energy loss module Matter.cc has some extra logic condition in the broadening section, otherwise the same broadening parton was pushed in twice.

pT-broadening issue #128 fixed

---

config/jetscape_main.xml
src/framework/JetScapeConstants.h
src/hadronization/ColorlessHadronization.cc
src/hadronization/ColorlessHadronization.h
src/hydro/Brick.cc
src/initialstate/epemGun.cc
src/initialstate/epemGun.h
src/jet/Matter.cc
src/jet/Matter.h

This PR implements:
- Removal of the `ini` pointer in the Brick module.
- Revert the change from JS 3.6.1, where `Lambda_QCD` was made a parameter in the XML file. This is the result of the discussion with @amajumder after the COMP meeting today. We will use this as a variable parameter in private branches or forks of the repository, but not in the publicly available code, where any user can change the value easily. This has too much potential to mess up the physics results by inexperienced users.

Fix ini pointer and revert Lambda_QCD changes

---

config/jetscape_user_pbpb_grid.xml

Per https://github.com/JETSCAPE/JETSCAPE/pull/168 , the `useHybridHad` config option was noted to be obsolete and was removed from most configuration files, including the `jetscape_main.xml` (I haven't yet found the commit that actually makes the option obsolete, so it would be good to confirm. Searching the codebase yields no other references to it, so I think it's fine). However, it appears that this configuration file was overlooked in removing the option, which prevents it from running. This PR removes the option
cc: @LipeiDu

Remove obsolete option in AA user config

---

config/jetscape_main.xml
src/hadronization/iSpectraSamplerWrapper.cc

As pointed out by @LipeiDu, some iSS parameters need to be changed by hand. Update the framework wrapper so that important parameters can be passed via XML to iSS.

add iSS parameters to JETSCAPE xml file

---

src/hadronization/HybridHadronization.cc

This fixes a bug where parameters are not reset to their original values after the first event in vacuum systems where no negative partons are present and the loop is exited early to avoid crashes in PYTHIA. The fix is only relevant if the hadrons should continue to propagate in the hadronic afterburner phase.
This closes #228.

Fix bug when not decaying hadrons Hybrid Hadronization (Pythia)

---

src/afterburner/SmashWrapper.h

This closes #225. When the hadron list is empty, then SMASH will start at t=0 to avoid infinite runtime.

Fix infinite loop when input for SMASH is empty

---

examples/test_music_files/music_input

When both pre-equilibrium and hydro outputs evolution history to memory, one needs to set output_evolution_every_N_timesteps to 1 in music_input.
This is because the free-streaming module does not support skipping time step output evolution.

fixed the time step for output evolution history

---

config/jetscape_main.xml
external_packages/get_freestream-milne.sh
external_packages/get_music.sh
src/preequilibrium/FreestreamMilneWrapper.cc

This closes #236 and it also implements the automatic determination of grid parameters for the free streaming module from the initial state module. The user can now use the `ntau` key in the XML file to determine the time steps in the free streaming phase.
@chunshen1987 This has to be tested. @ritobandatta will run a few more tests.

Fix density rotation bug / FS automatic parameter determination

---

.github/workflows/test-build-external.yaml
.github/workflows/test-build-macos-native.yaml
.github/workflows/test-events-PbPb.yaml
.github/workflows/test-events-brick.yaml
.github/workflows/test-events-pp.yaml
external_packages/gtl/include/GTL/GTL.h
external_packages/gtl/src/bid_dijkstra.cpp
external_packages/gtl/src/dijkstra.cpp

This PR resolves the compilation issue when using Clang 16 by removing the binary_function inheritance in the GTL library.
GitHub Actions workflows are also added to test that JETSCAPE compiles on native Mac hardware.  Separate workflows use Clang 15 and Clang 16, so both compilers are verified.
https://github.com/JETSCAPE/JETSCAPE/actions/runs/11506333653
This test compiles JETSCAPE on native Mac runners with the external packages Music, iSS, Freestream, and Smash turned on.
runJetscape with [arXiv_1910.05481/jetscape_user_PP_1910.05481.xml](https://github.com/JETSCAPE/JETSCAPE/blob/main/config/publications_config/arXiv_1910.05481/jetscape_user_PP_1910.05481.xml) is then executed just to ensure that JETSCAPE runs and exits successfully.
Would it be preferred for the clang 16 GTL fix to …

remove gtl binary_function & add macOS workflow

---

.github/workflows/test-build-external.yaml
.github/workflows/test-build-macos-native.yaml
.github/workflows/test-code-format.yaml
.github/workflows/test-events-PbPb.yaml
.github/workflows/test-events-brick.yaml
.github/workflows/test-events-pp.yaml
CMakeLists.txt
external_packages/gtl/include/GTL/GTL.h
external_packages/gtl/src/bid_dijkstra.cpp
external_packages/gtl/src/dijkstra.cpp

This PR applies the GTL modification to the JETSCAPE 4.0 release candidate branch, and adds a GitHub Actions workflow to test the installation on native Mac runners using Clang 15 and Clang 16.
This PR replaces PR #234, which was directed to the 3.6.5 main branch.  For this PR, which is directed to the 4.0 release candidate, CMakeLists was modified so Clang can find OpenMP, which is needed for ThermalPartonSampler in the 4.0 release candidate.

GTL Modification and Native Mac Workflow

---

.github/workflows/test-build-external.yaml
.github/workflows/test-build-macos-native.yaml
.github/workflows/test-events-PbPb.yaml
.github/workflows/test-events-brick.yaml
.github/workflows/test-events-pp.yaml
CMakeLists.txt

This modernizes the CMakeLists syntax requiring C++17 so it will work on newer compilers.

update C++17 requirement CMakeLists syntax

---

config/jetscape_main.xml
config/publications_config/arXiv_2011.01430/jetscape_user_AA_2011.01430.xml
src/preequilibrium/FreestreamMilneWrapper.cc

This PR adds the energy density-dependent free streaming end time to the XML parameters.
I switched this off as a default and switched it on in the soft AA paper calibration paper XML. This way, the `taus` parameter really has the meaning one would expect. I also adjusted the value of `taus` to be 0.5 fm as a default, which is the default MUSIC `Initial_time_tau_0`.

Additional free streaming parameters in XML

---

config/jetscape_main.xml
examples/FinalStateHadrons.cc
examples/FinalStatePartons.cc
src/framework/JetScapeWriterFinalStateStream.cc
src/framework/JetScapeWriterFinalStateStream.h

Add optional ability to filter on the status code for the particles written in the final state {hadron,parton} readers.
NOTE: This also contains a separate fix from Chun, so that needs to be merged/removed first. It's currently being tested, and then this PR will be updated and changed from draft -> ready

Add option to filter on status code for final state hadrons

---

config/jetscape_user_PbPb_hard_nPDF.xml

This closes #248.
The nPDF setting is removed from the AA paper XML. The same file with the nPDF setting is stored in the `config` directory with the name `jetscape_user_PbPb_hard_nPDF.xml`.

Remove nPDF settings from AA hard paper XML and copy to separate XML

---

config/jetscape_main.xml
external_packages/get_ipglasma.sh
src/initialstate/IPGlasmaWrapper.cc
src/preequilibrium/Glasma.cc
src/preequilibrium/Glasma.h

Following the current preEquilibrium module, we update the Glasma preEq module in JETSCAPE accordingly. This module is a fake wrapper, which only reads in the Tmunu from a local file and passes it to hydro. 
I correct the units in the Glasma module to avoid double counting when passing the Tmunu to MUSIC.

update the Glasma preEq wrapper

---

.github/workflows/test-build-external.yaml
.github/workflows/test-build-macos-native.yaml
.github/workflows/test-events-PbPb.yaml
.github/workflows/test-events-brick.yaml
.github/workflows/test-events-pp.yaml
external_packages/README.md

This PR adds IP-Glasma to the external packages automated build test and updates the installation instructions in the external packages README.
I will change the Docker tag references in the test workflows from **v1.10** to **stable** when the v1.10 image is tagged as stable for the release.

Add IP-Glasma to Build Test and Update README Instructions

---

config/jetscape_main.xml
src/framework/InitialState.cc
src/framework/InitialState.h
src/framework/JetScapeEventHeader.h
src/framework/JetScapeWriterFinalStateStream.cc
src/framework/JetScapeWriterFinalStateStream.h
src/initialstate/TrentoInitial.cc
src/initialstate/TrentoInitial.h

This update is based on 3.6.7-RC. It addresses a bug related to the mismatch between centrality bins and their corresponding densities. Additionally, it implements event-by-event centrality determination based on Trento initial conditions, using the centrality bin table. The centrality of an event can optionally be written to the event header.

Centrality table update

---

.github/workflows/test-build-external.yaml
CMakeLists.txt
external_packages/README.md

This makes the CMake flag for IP-Glasma similar to the ones for the other external packages (all capital letters) to avoid confusion for the user.

Make IP-Glasma CMake flag similar to other external codes

---

config/jetscape_main.xml
src/framework/JetScapeWriterFinalStateStream.cc

We write the number of particles into the event header, but if we filter particles, this number in the header won't match the number that's actually written.
(I had actually fixed this in a separate branch, but forgot to merge it when we merged the filtering - sorry!)

Bug fix for filtering final state particles in writer

---

src/hydro/HydroFromFile.cc

The Vz flow for the boost-invariant case in IP-GLASMA, read from a saved file, has been corrected. Previously, the getHydroInfo function mistakenly always retrieved the z-coordinate of the fluid cell as τ_{local} * sinh⁡(0).

Vz fix IP-GLASMA Grid Saved

---

src/framework/JetScapeWriterQnCalculator.cc
src/framework/JetScapeWriterQnCalculator.h

- The grid numbers and sizes for rapidity and pT, along with the number of harmonics are written in the header of the Qn vector output file.
- The event centrality for each event can be optionally written.
- Some empty lines are removed from the source code.
- Tested.

Write more info in the Qn vector output file (Enhancement #276)

---

.github/workflows/test-build-external.yaml
.github/workflows/test-build-macos-native.yaml
.github/workflows/test-build-nPDF.yaml
.github/workflows/test-events-PbPb.yaml
.github/workflows/test-events-brick.yaml
.github/workflows/test-events-pp.yaml
CMakeLists.txt
external_packages/CMakeLists.txt
external_packages/clvisc_wrapper/CMakeLists.txt
external_packages/googletest/CMakeLists.txt
external_packages/googletest/googlemock/CMakeLists.txt
external_packages/googletest/googletest/CMakeLists.txt
external_packages/googletest/googletest/README.md
external_packages/gtl/CMakeLists.txt
external_packages/gtl/src/CMakeLists.txt
external_packages/gtl/tests/CMakeLists.txt
external_packages/hydro_from_external_file/CMakeLists.txt
external_packages/trento/CMakeLists.txt
src/CMakeLists.txt

This PR updates JETSCAPE's CMakeLists minimum version required parameter to 3.5 from 3.0, as the new cmake 4.0 requires projects built using cmake to require cmake 3.5 as a minimum.
Also, the GitHub Actions workflow that builds and tests a native MacOS installation has been updated to install cmake, Pythia 8.309, and HepMC3 3.2.6 from source instead of from Homebrew or Homebrew taps.  This resolves the issue where checking out older brew commits to get these specific older versions of Pythia and HepMC3 failed on account of the new cmake minimum requirement.

Updates minimum cmake required to 3.5 and installs MacOS workflow packages from source
