JETSCAPE/JETSCAPE

- examples/jetscape_init.xml
- src/jet/Martini.cc
- src/jet/Martini.h
- bug fix in getNewMomentumElas()
- Minor clean up (remove 'cout' and 'cerr') 
- add set_jet_v() for each parton
- add hydro_Tc and Q0 parameter
Tested (brickTest, PythiaBrickTest, hydroJetTest)
> Apply Pull Request #192 in private repo

- src/jet/Martini.cc
- src/jet/Martini.h
- Warning for large deltaT at Init() : If Martini module is linked and deltaT in XML is greater than 0.01, Martini:Init() prints out a warning message for user to set deltaT smaller than or equal to 0.01.
- Hydro initialization time : Update the position of a given parton by taking free propagation into account until hydro is initialized.
> Apply Pull Request #196 in private repo

- README_LINUX.md
Ebrahim, can you check that all is right now? These instructions were quite old.
> Updated instructions for Linux

- README.md
Update the readme file regarding to the new version of MUSIC
> update Readme file for new MUSIC

- examples/PythiaBrickTest.cc
- external_packages/trento/CMakeLists.txt
Added summary of event information in the PythiaBrickTest.cc
> School support for hand-on session

- src/framework/JetScapeSignalManager.cc
When you approve and merge this, please remove its associated branch.
> Fix the memory leak in JetScapeSignalManager.

- src/hydro/MusicWrapper.cc
Fixed the line pointed out by Wilke.
> fixed bug pointed out by Wilke.

- cmakemodules/FindSMASH.cmake
This refs issue #43
Signed-off-by: Dmytro Oliinychenko <doliinychenko@lbl.gov>
> Fix SMASH includes

- external_packages/README.md
Do not store info that gradually gets outdated,
instead refer to original SMASH documentation,
Besides the fact that it is a reasonable idea, Hannah recently asked me to do this.
Signed-off-by: Dmytro Oliinychenko <doliinychenko@lbl.gov>
> Update SMASH installation instructions

- config/jetscape_master.xml
- src/hadronization/iSpectraSamplerWrapper.cc
- src/hydro/MusicWrapper.cc
Update the interface iSpectraSamplerWrapper.cc to the latest version of iSS.
> Update the interface for iSS

- config/jetscape_user_twostagehydro.xml
- examples/unittests/causal_liquifier.cc
- src/liquefier/CausalLiquefier.cc
- src/liquefier/CausalLiquefier.h
(from Yasuki)
An update of Liquefier with corrected formulae is done.
XML inputs for Liquefier are also added.
> Release3.0 liquefier update

- src/framework/Hadronization.h
- src/framework/HadronizationManager.cc
- src/framework/HadronizationManager.h
- src/framework/JetScape.cc
- src/framework/JetScapeSignalManager.cc
- src/framework/JetScapeSignalManager.h
- src/framework/JetScapeWriterStreamFilter.h
- src/jet/HadronPrinter.cc
- src/jet/HadronPrinter.h
> Particle writer pull request 

- config/jetscape_master.xml
- examples/FinalStateHadrons.cc
- examples/FinalStatePartons.cc
- src/framework/FluidDynamics.cc
- src/framework/FluidDynamics.h
- src/framework/Hadronization.cc
- src/framework/Hadronization.h
- src/framework/HadronizationManager.cc
- src/framework/JetScape.cc
- src/framework/JetScapeSignalManager.cc
- src/framework/JetScapeSignalManager.h
- src/framework/JetScapeWriterFinalStateStream.cc
- src/framework/JetScapeWriterFinalStateStream.h
- src/hydro/MusicWrapper.cc
- src/reader/JetScapeReader.cc
- src/reader/JetScapeReader.h
add signal slot connections to get hydrodynamic hypersurface in the hadronization module.
> Connect hydro surface with hadronization

- src/hydro/HydroFromFile.cc
Fixed the velocity calculation when using VISH2+1 medium files
> fixed the hydro reader for VISH2+1 evolution files

- .github/workflows/plot_observables.yaml
- test/plot/plot_results.py
Modified YAML to include PR Number as an environment variable to be used by plot_result.py (which was also modified to include the current date and PR number in the files generated.
> date pr in filenames

- src/jet/LBT.cc
- src/jet/Matter.cc
PR to incorporate Shanshan's patch. This breaks out of the colljet22 loops if it can't find a suitable value after many iterations.
Amit has tested the code and the patch is working.
Once this PR is approved, we will release a patch release, Jetscape 3.5.1, to make this fix and a few other smaller changes available.
> Fix #124 Handle rare case where Matter/LBT can loop

- src/hydro/MusicWrapper.h
Fix the units inconsistency between the Liquefier and MUSIC.
> fixed the unit for liquefier source deposited to MUSIC

- config/jetscape_main.xml
- config/jetscape_user_MUSIC.xml
- external_packages/get_music.sh
- src/hydro/MusicWrapper.cc
(1) Use the specialized MUSIC version for JETSCAPE (more than 2x boost in speed)
This specialized version is developed for the XSCAPE project and has backward compatibility.
(2) Add a user xml to run Trento + MUSIC + iSS
(3) Update parameter names in the MUSIC wrapper
> MUSIC Updates

- config/jetscape_main.xml
- src/framework/JetScape.cc
Fixing debug xml parameter implementation.
> Fixing issue Debug setting in xml #170

- src/framework/FourVector.h
This PR applies the changes to FourVector.h from JETSCAPE-COMP.
> includes FourVector updates from JETSCAPE-COMP

- config/jetscape_main.xml
- src/hydro/HydroFromFile.cc
- src/initialstate/NcollListFromFile.cc
Updates for reading in hydro evolution files from IPGlasma + MUSIC simulations.
> update the code base to read in hydro evolution from IPGlasma

- .github/workflows/test-events-brick.yaml
This adds the Brick Matter Lbt test to the automated tests that run on pushes and pull requests.
> Includes Brick Matter Lbt Automated Test

- .github/ISSUE_TEMPLATE/01-bug_report.yml
- .github/ISSUE_TEMPLATE/02-enhancement.yml
- .github/ISSUE_TEMPLATE/config.yml
This PR implements GitHub Issue Template Forms for bug reports and enhancements.
Since this PR only adds YAML files for repository management on GitHub and doesn't touch any of the JETSCAPE source code, no version number update is applied.
> Implements GitHub Issue Template Forms

- config/jetscape_main.xml
- src/initialstate/PythiaGun.cc
- src/initialstate/PythiaGun.h
- src/initialstate/epemGun.cc
- src/jet/Matter.cc
- src/jet/Matter.h
This fixes a bug when a negative `vir_factor` is used in the PythiaGun. The other files are changed due to the updates on the main branch, where the branch is based.
> Fix vir_factor in PythiaGun

- config/jetscape_main.xml
- src/framework/LiquefierBase.cc
- src/framework/LiquefierBase.h
This adds the `e_threshold` in the liquefier to the XML file. To capture the different meaning with positive and negative sign another flag is introduced.
> Add new parameters to liquefier

- src/reader/JetScapeReader.cc
Fixes the reader's event heading reading.
> adding extra dummy iteration to event header reading

- .vscode/settings.json
- src/framework/SurfaceFinder.cc
- src/framework/SurfaceFinder.h
- src/framework/SurfaceFinder_legacy.cc
- src/framework/SurfaceFinder_legacy.h
- Merging the changes for surface finder class into a newly made branch in the JETSCAPE organization related to its name.
- The main branch is originated form (https://github.com/JETSCAPE/JETSCAPE/tree/JETSCAPE-4.0-RC)  which finally every improvement will be merged to it as well.
> Hmehryar code optimization surface finder

- .github/workflows/test-build-external.yaml
- .github/workflows/test-events-PbPb.yaml
- .github/workflows/test-events-brick.yaml
- .github/workflows/test-events-pp.yaml
- README.md
- examples/test_music_files/music_input
- src/afterburner/SmashWrapper.h
- src/hadronization/HybridHadronization.cc
merges JETSCAPE-3.6.5-RC to main for the JETSCAPE 3.6.5 release.
> Jetscape 3.6.5 rc

- .github/workflows/test-build-external.yaml
- .github/workflows/test-build-macos-native.yaml
- .github/workflows/test-events-PbPb.yaml
- .github/workflows/test-events-brick.yaml
- .github/workflows/test-events-pp.yaml
- README.md
- config/jetscape_main.xml
- external_packages/get_freestream-milne.sh
- external_packages/get_music.sh
- external_packages/gtl/include/GTL/GTL.h
- external_packages/gtl/src/bid_dijkstra.cpp
- external_packages/gtl/src/dijkstra.cpp
- src/preequilibrium/FreestreamMilneWrapper.cc
This PR merges the JETSCAPE 3.6.6 RC branch to main for the JETSCAPE 3.6.6 release.
> Jetscape 3.6.6 rc

- config/jetscape_user_IPGlasmaMUSIC.xml
> update the default xml for IP-Glasma + MUSIC

- src/preequilibrium/Glasma.h
> Fix glasma time to remove time shift in stored evolution

- config/jetscape_main.xml
- src/framework/InitialState.cc
- src/framework/InitialState.h
- src/framework/JetScapeEventHeader.h
- src/framework/JetScapeWriterFinalStateStream.cc
- src/framework/JetScapeWriterFinalStateStream.h
- src/initialstate/TrentoInitial.cc
- src/initialstate/TrentoInitial.h
Reverts JETSCAPE/JETSCAPE#252
I tried running a xml with your changes merged into the RC, but it looks like that the simulation is getting stuck in an endless loop.
> Revert "Centrality table update"

- config/jetscape_main.xml
- src/framework/InitialState.cc
- src/framework/InitialState.h
- src/framework/JetScapeEventHeader.h
- src/framework/JetScapeWriterFinalStateStream.cc
- src/framework/JetScapeWriterFinalStateStream.h
- src/initialstate/TrentoInitial.cc
- src/initialstate/TrentoInitial.h
> Revert "Revert "Centrality table update""

- src/framework/JetScapeWriterQnCalculator.cc
I added a condition statement to only include hadrons from iSS (status = 11) and SMASH (status = 27) in the QnVector writer
> Qnvector issue

- src/reader/JetScapeReaderFinalStateHadrons.cc
- src/reader/JetScapeReaderFinalStateHadrons.h
Lets you read FinalStateHadron files in c++ without needing python
> adding FinalStateHadrons c++ reader

- config/jetscape_main.xml
- examples/convert_binary_to_ASCII_output.py
- src/framework/JetScapeWriterFinalStateStream.cc
- src/framework/JetScapeWriterFinalStateStream.h
This brings [PR 85](https://github.com/JETSCAPE/X-SCAPE/pull/85) from X-SCAPE 1.2 to JETSCAPE.
> add a binary output mode for the final state hadron/parton outputs

- .github/workflows/test-build-external.yaml
- .github/workflows/test-build-macos-native.yaml
- .github/workflows/test-build-nPDF.yaml
- .github/workflows/test-events-PbPb.yaml
- .github/workflows/test-events-brick.yaml
- .github/workflows/test-events-pp.yaml
- CMakeLists.txt
- README.md
- config/jetscape_main.xml
- examples/convert_binary_to_ASCII_output.py
- external_packages/CMakeLists.txt
- external_packages/clvisc_wrapper/CMakeLists.txt
- external_packages/googletest/CMakeLists.txt
- external_packages/googletest/googlemock/CMakeLists.txt
- external_packages/googletest/googletest/CMakeLists.txt
- external_packages/googletest/googletest/README.md
- external_packages/gtl/CMakeLists.txt
- external_packages/gtl/src/CMakeLists.txt
- external_packages/gtl/tests/CMakeLists.txt
- external_packages/hydro_from_external_file/CMakeLists.txt
- external_packages/trento/CMakeLists.txt
- src/CMakeLists.txt
- src/framework/JetScapeWriterFinalStateStream.cc
- src/framework/JetScapeWriterFinalStateStream.h
- src/framework/JetScapeWriterQnCalculator.cc
- src/framework/JetScapeWriterQnCalculator.h
- src/hydro/HydroFromFile.cc
- src/reader/JetScapeReaderFinalStateHadrons.cc
- src/reader/JetScapeReaderFinalStateHadrons.h
This PR merges the JETSCAPE 3.7.1 RC branch to main for the JETSCAPE 3.7.1 release.
> JETSCAPE 3.7.1 Release
